apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: my-backend-container
        image: 273354639531.dkr.ecr.ap-southeast-1.amazonaws.com/bawa0017:backend-20
        envFrom:
          - secretRef:
              name: my-secret
        ports:
        - containerPort: 5001
      nodeSelector:
        front: back
