apiVersion: "apps/v1" 
kind: "Deployment" 
metadata: 
  name: "mongo-db"
spec: 
  selector: 
    matchLabels: 
      app: "mongo-db"
  replicas: 1
  strategy: 
    type: "RollingUpdate"
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5  
  template: 
    metadata: 
      labels: 
        app: "mongo-db"
    spec: 
      containers:  
        - 
          name: "mongo-db"
          image: "mongo:latest"
          imagePullPolicy: "Always" 
          env: 
            - 
             name: "MONGO_INITDB_ROOT_USERNAME"
             valueFrom: 
               secretKeyRef:
                  name: my-secret
                  key: username             
                 
            -
             name: "MONGO_INITDB_ROOT_PASSWORD"
             valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: password
                
          ports: 
            -            
              containerPort: 27017
              name: "mongodb"
                
          volumeMounts: 
            - 
              name: "pvc-db"
              mountPath: "/data/db"
                
      volumes: 
        - name: "pvc-db"
          persistentVolumeClaim: 
            claimName: "pvc-db"