apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-db
spec:
  accessModes:
    - ReadWriteOnce # This access mode is typically used for local storage
  resources:
    requests:
      storage: 5Gi # Request 5 Gigabytes of storage
  storageClassName: local-storage # This refers to a StorageClass named "local-storage"