apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-db
  namespace: test01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2  # or gp2
